branches:
  except:
    - gh-pages
language: perl6
services:
  - couchdb
sudo: false
perl6:
  - latest
install:
  - rakudobrew build-panda
  - panda --notests install JSON::Fast
  - panda --notests installdeps .
